pipeline {
   node any {
      stages {
         stage('test') {
            nodejs(nodeJSInstallationName: 'nodejs') {
            sh 'npm install --only=dev'
            sh 'npm test'
            }   
         }
         stage('docker build/push') {
            docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
            def app = docker.build("cooldsachin/docker-nodejs-demo:${BUILD_ID}", '.').push()
            }
         }      
      }
   }   
}
