pipeline {
   agent any
      stages {
         stage('test') {
            steps {
               nodejs(nodeJSInstallationName: 'nodejs') {
               sh 'npm install --only=dev'
               sh 'npm test'
               }   
            }
         }   
         stage('docker build/push') {
            steps {
               docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
               def app = docker.build("cooldsachin/docker-nodejs-demo:${BUILD_ID}", '.').push()
               }
            }      
         }
      }    
      
}
